# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80a4ee6e97b3c32fa038209120640c2d5c0e5c2f85ff4050c072a510f8ab2817957ae3204edbd99a17635dc3015701dcccac7bfce3ea2d809134e78c3caeb7f7

test:
  secret_key_base: 11a6ab74b681d01c458e05bdd291d994bbcce72e47fddc85f6cc22f7a420fc58018727c5f9f63900dc2c74fbcf675aa7c3b51015aa9ec99cf77bc6ad88bcb452

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
